# Generated by Django 2.2 on 2020-08-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cost',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='available_shares',
            new_name='quantity',
        ),
    ]
