# Generated by Django 2.2 on 2020-08-25 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradingapp', '0002_auto_20200825_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='tradingapp.Stock'),
        ),
        migrations.AlterField(
            model_name='order',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='profiles.Profile'),
        ),
    ]
